# Stale Action

# This action automatically closes old issues to maintain repository cleanup
# Cron runs the job at 13:00 German local time (CET/CEST)
# GitHub Actions cron uses UTC, so the time is set to 11:00 UTC.
# Exemptions: Issues with milestones or labels 'ref/IP', 'ref/NC' are skipped.
# days-before-issue-stale: Days until issue gets 'stale' label.
# Set to 1304 days to represent 5 years of working days (Mon–Fri),
# because the cron job only runs on weekdays.
# days-before-issue-close: 0: Issues are closed immediately after being labeled stale
# operations-per-run: 15: Max ~5 issues processed per run (3 operations each)
# ascending: true: Processes oldest issues first
# ignore-issue-updates: true: Closes issues regardless of recent activity
# debug-only: action only simulates the labeling and closing process, useful for testing
# Reopen: Automatically closed issues must be manually reopened if still relevant, and the 'stale' label removed to prevent reprocessing.

name: 'stale with PR'

#permissions:
#  issues: write

on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 11 * * 1-5


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          close-issue-message: 'This issue has been automatically closed due to age/inactivity. If still relevant with current software version, feel free to create a new issue with updated details. '
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'ref/IP, ref/NC'
          exempt-all-issue-milestones: true
          days-before-stale: 0
          days-before-close: 0
          operations-per-run: 50
          enable-statistics: true
          ignore-issue-updates: true
          ascending: true
          debug-only: false
