name: 'stale overwrite pr default'

permissions:
  issues: write

on:
  workflow_dispatch:


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          close-issue-message: 'This issue has been automatically closed due to age/inactivity. If still relevant with current software version, feel free to create a new issue with updated details.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'ref/IP, ref/NC'
          exempt-all-issue-milestones: true
          days-before-issue-stale: 0
          days-before-issue-close: 0
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 50
          enable-statistics: true
          ignore-issue-updates: true
          ascending: true
          debug-only: false

